---
- name: Configurar NTP en el Servidor FreeIPA
  hosts: freeipa_servers
  become: yes
  gather_facts: no # Evita errores en sistemas minimalistas

  tasks:
  
    - name: Verificar sistema operativo en FreeIPA
      ansible.builtin.raw: "hostnamectl"
      register: os_check
      ignore_errors: true

    - name: Mostrar información de sistema operativo
      debug:
        var: os_check.stdout
    - name: Instalar net-tools en FreeIPA
      ansible.builtin.package:
        name: net-tools
        state: present

    - name: Instalar chrony en FreeIPA
      ansible.builtin.yum:
        name: chrony
        state: present

    - name: Configurar chrony en FreeIPA como servidor NTP
      ansible.builtin.copy:
        dest: /etc/chrony.conf
        content: |
          pool europe.pool.ntp.org iburst
          server 10.17.3.11 iburst prefer
          allow 10.17.3.0/24
          allow 10.17.4.0/24
          local stratum 10 orphan
      notify:
        - Reiniciar chronyd

    - name: Iniciar y habilitar chronyd en FreeIPA
      ansible.builtin.systemd:
        name: chronyd
        enabled: true
        state: started

    - name: Recargar fuentes de tiempo en chronyd
      ansible.builtin.command: "chronyc reload sources"
      changed_when: false

    - name: Forzar selección de fuentes NTP en chronyd
      ansible.builtin.command: "chronyc reselect sources"
      changed_when: false

    - name: Forzar sincronización inmediata de NTP
      ansible.builtin.command: "chronyc makestep"
      changed_when: false

    - name: Verificar si el puerto 123 está abierto en FreeIPA
      ansible.builtin.command: "netstat -tulpn | grep ':123' || true"
      register: ntp_port
      changed_when: false
      ignore_errors: true

    - name: Mostrar estado del puerto 123 en FreeIPA
      debug:
        var: ntp_port.stdout_lines

    - name: Abrir puerto NTP en el firewall de FreeIPA
      ansible.builtin.firewalld:
        service: ntp
        permanent: true
        immediate: yes
        state: enabled

    - name: Verificar estado de chronyd
      ansible.builtin.command: "chronyc tracking"
      register: chronyd_status
      changed_when: false

    - name: Mostrar estado de sincronización de chronyd
      debug:
        var: chronyd_status.stdout

    - name: Verificar fuentes de tiempo de chronyd
      ansible.builtin.command: "chronyc sources -v"
      register: chronyd_sources
      changed_when: false

    - name: Mostrar fuentes de sincronización de chronyd
      debug:
        var: chronyd_sources.stdout

  handlers:
    - name: Reiniciar chronyd
      ansible.builtin.systemd:
        name: chronyd
        state: restarted
