---
- name: Configurar NTP en el Servidor FreeIPA
  hosts: freeipa_servers
  become: yes
  gather_facts: no # Evita errores por falta de Python en sistemas minimalistas

  tasks:
    - name: Verificar sistema operativo en FreeIPA para asegurarse de que es compatible
      ansible.builtin.raw: "hostnamectl"
      register: os_check
      ignore_errors: true

    - name: Mostrar información de sistema operativo (para depuración)
      debug:
        var: os_check.stdout

    - name: Instalar chrony en FreeIPA (Servidor NTP)
      ansible.builtin.yum:
        name: chrony
        state: present

    - name: Configurar chrony en FreeIPA para servir como NTP y permitir acceso a la red
      ansible.builtin.copy:
        dest: /etc/chrony.conf
        content: |
          pool europe.pool.ntp.org iburst
          server time.netzwerge.de iburst prefer
          server x1.ncomputers.org iburst
          server mail.somenet.org iburst
          server ip99.mikrocom.sk iburst
          allow 10.17.3.0/24
          allow 10.17.4.0/24
          local stratum 10
      notify:
        - Reiniciar chronyd

    - name: Iniciar y habilitar chronyd en FreeIPA
      ansible.builtin.systemd:
        name: chronyd
        enabled: true
        state: started

    - name: Abrir puerto NTP en el firewall de FreeIPA
      ansible.builtin.firewalld:
        service: ntp
        permanent: true
        immediate: yes
        state: enabled

    - name: Verificar si nftables está en uso
      ansible.builtin.command: "nft list ruleset"
      register: nft_status
      ignore_errors: true
      changed_when: false

    - name: Agregar regla para permitir tráfico NTP en nftables si está en uso
      ansible.builtin.command: "nft add rule ip filter input udp dport 123 accept"
      when: "'filter' in nft_status.stdout"
      ignore_errors: true

    - name: Verificar estado de chronyd
      ansible.builtin.command: "chronyc tracking"
      register: chronyd_status
      changed_when: false

    - name: Verificar fuentes de tiempo de chronyd
      ansible.builtin.command: "chronyc sources -v"
      register: chronyd_sources
      changed_when: false

    - name: Mostrar estado de sincronización de chronyd
      debug:
        var: chronyd_status.stdout

    - name: Mostrar fuentes de sincronización de chronyd
      debug:
        var: chronyd_sources.stdout

    - name: Forzar sincronización inmediata de NTP
      ansible.builtin.command: "chronyc makestep"
      changed_when: false

  handlers:
    - name: Reiniciar chronyd
      ansible.builtin.systemd:
        name: chronyd
        state: restarted